baseurl = 'https://koji0919.github.io/1be9abc2a2d91b83142e9ae8474bfa99d9905c2357ad367cbbee2d4a41037781/'
CanonifyURLs=true
relativeURLs=true

languageCode = 'ja-jp'
theme = "ramium"

title = "文献まとめβ"
disqusShortname = ""
googleAnalytics = ""
summaryLength = 140
pluralizeListTitles = false
enableemoji = false
enableRobotsTXT = true

[params]
    description = "A description for the meta tag of the site"
    googleSearch = ""
    adsense = ""
    showDate = true # make false if dont want to show date
    math = false # best to enable this in the front matter of a page
    githubProfile = "rafed/ramium/"

    tagsInHome = 40
    # sectionsInHome = 5 
    faviconImg = "image/ドクター.png"
    paginatePostsPerPage = 5
    paginateTagsPerPage = 6

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[menu]
    [[menu.main]]
        name = "ホーム"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "投稿"
        name = "投稿を検索"
        weight = 2
            [[menu.main]]
                parent = "投稿"
                name = "タグから探す"
                url = "/tags/"
                weight = 1
            [[menu.main]]
                parent = "投稿"
                name = "製品から探す"
                url = "/sections/"
                weight = 2
            [[menu.main]]
                parent = "投稿"
                name = "一覧"
                url = "/posts/"
                weight = 3
    
    [[menu.main]]
        name = "このサイトについて"
        url = "/author/"
        weight = 3

    [outputs]
        home = ["html", "rss", "json"]
